### ISSUE TITLE
Problem opening Github 'blob' content with space in file name.

### ISSUE THREAD

**Issue by mutterer** [imjoy-team/imagej.js#20]
Hi ImJoy Team,

I noticed that when opening the 'blob' version of a github macro, loading can fail if the file name has a SPACE character.
Example:

https://ij.imjoy.io/?open=https://github.com/mutterer/TD-NMatt/blob/main/hello%20world.ijm
doesn't work

https://ij.imjoy.io/?open=https://github.com/mutterer/TD-NMatt/blob/main/hello_world.ijm
works

Jerome.

**Comment by oeway** [comment]
Hi Jerome (@mutterer),

Thanks for the report, I have fixed this issue. You might need to refresh twice to get rid of the browser cache.
