### ISSUE TITLE
Fails on Firefox due to disallowed call to Google docs

### ISSUE THREAD

**Issue by jkh1** [imjoy-team/imagej.js#31]
On Firefox, I get the following error messages in the console when visiting https://ij.imjoy.io/:
Reporting error: SecurityError: Permission denied to access property "dispatchEvent" on cross-origin object/onUserInput/<@moz-extension://4bf5f5be-0ca4-4c6c-b196-a7b195f5a34b/js/inject.js:65:9
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://docs.google.com/forms/d/e/1FAIpQLScErDRKZvSy1JAdiRSZfAsjf711VWdSdkczuSYHfIHQbtyFXA/formResponse. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

It's trying to access Google docs without disclosing it (it looks like it's a CheerpJ bug report form but could be anything really) and could be illegal from a GDPR point of view. I would suggest removing this.

**Comment by oeway** [comment]
Hi, thanks for reporting. Yes, that's the bug report form used by cheerpj. I will pass this message to the cheerpj team.
