### ISSUE TITLE
Font display is not normal in Windows 10

### ISSUE THREAD

**Issue by ethanzhao9** [imjoy-team/imagej.js#36]
Hi, I am Ethan. I am using Win10 and Chrome to run imagej.js.
The font display is not normal when I try to adjust threshold and set measurements. 
Some long strings just wrap around and block buttons.
Some fonts of set measurements are not displayed.
![image](https://user-images.githubusercontent.com/42763479/99905993-65c37600-2d0f-11eb-807e-c87330cea6ef.png)
![image](https://user-images.githubusercontent.com/42763479/99906073-dc607380-2d0f-11eb-9483-962356358c39.png)

It didn't become normal when I changed the size of whole website. Hope you can fix it.

Best.

**Comment by oeway** [comment]
Hi @ethanzhao9 Could you try to change the `font-family` from `sans-serif` to `Arial, Helvetica, sans-serif` and see how it works?

See the GIF below:
![change-font](https://user-images.githubusercontent.com/478667/99978593-6c50fc80-2da6-11eb-8377-1f52ec70780b.gif)

**Comment by oeway** [comment]
Update: I did the above fix in the released version, so you don't need to do the test described above. Let me know if it works for you with the latest version. thanks!

**Comment by gywgithub** [comment]
This problem is confirmed to be fixed.
![20201118143616](https://user-images.githubusercontent.com/6777859/100070025-66c1e800-2e74-11eb-82de-acb0fb8e32a9.png)

**Comment by oeway** [comment]
Thanks @gywgithub ! So the font was the issue then.

I will close this issue for now. @ethanzhao9 if you encountered anything, please reopen the issue or comment here, thank you.
